### ISSUE TITLE
Question of PSAP

### ISSUE THREAD

**Issue by rscgg37248** [Guido497/phase-separation#1]
Hi, I met some questions about PSAP. I wanna test the pretrained model, but it always showed 'wrong' after I installed iupred from its website. The code goes error in the first step, said 'can't find iupred_lib', and stopped at IDR_iupred function-amino_acid_analysis. I wanna know the correct step to install iupred and successfully call its code. Thank you.

**Comment by Guido497** [comment]
Sorry for taking some time to get back to you. The iupred module gives some issues at times indeed. After downloading the most recent module from IUPred2a, could you import it as:

from iupred2a import iupred2a_lib

Also in the section def calc_idrpred(args): you will have to adapt it to iupred2a_lib.iupred instead of iupred2a.iupred

Let me know if this works.

**Comment by rscgg37248** [comment]
Thanks！I've solved it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guido497/phase-separation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guido497/phase-separation] Question of PSAP (Issue #1)





 
Sorry for taking some time to get back to you. The iupred module gives some issues at times indeed. After downloading the most recent module from IUPred2a, could you import it as:
 
from iupred2a import iupred2a_lib
 
Also in the section def calc_idrpred(args): you will have to adapt it to iupred2a_lib.iupred instead of iupred2a.iupred
 
Let me know if this works.
